-- LAWgico Compromissos — automações "quando Status muda pra Entregue, notifica"
-- Rodar no SQL Editor do projeto Supabase rpibvjcnrseuugpkfmdj

create table public.compromissos_automacoes (
  id bigint generated by default as identity primary key,
  nome text not null,
  escopo_tipo text not null default 'todos',   -- 'todos' | 'grupo' | 'pessoa'
  escopo_valor text,                            -- nome do grupo ou da pessoa (null quando escopo_tipo='todos')
  email_notificar text not null,
  ativo boolean not null default true,
  criado_em timestamptz default now()
);
alter table public.compromissos_automacoes enable row level security;
create policy "anon full access" on public.compromissos_automacoes for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.compromissos_automacoes;

-- Seed: reproduz o comportamento atual do notificar_conclusao.py (1 e-mail
-- pra controladoria@ com tudo que foi marcado entregue) como a automação
-- padrão "Todos" — dá pra desativar ou editar depois pela tela.
insert into public.compromissos_automacoes (nome, escopo_tipo, escopo_valor, email_notificar, ativo)
values ('Padrão — todos os compromissos', 'todos', null, 'controladoria@peixotoecury.com.br', true);

NOTIFY pgrst, 'reload schema';
