-- LAWgico Compromissos
-- Rodar no SQL Editor do projeto Supabase rpibvjcnrseuugpkfmdj

create table public.compromissos_definicoes (
  id bigint generated by default as identity primary key,
  origem text not null,                  -- 'atividade' | 'pauta' | 'relatorio'
  responsavel_nome text,
  responsavel_sigla text,
  responsavel_email text,
  grupo text,
  cliente text,
  item text,
  etapa text,                            -- ex: 'Elaboração da Pauta', 'Corte', 'Envio ao cliente'
  periodicidade_original text,           -- texto bruto da planilha, so pra conferencia
  regra_tipo text not null,              -- 'diaria' | 'dias_semana' | 'fim_de_mes' | 'dia_mes' | 'indefinida'
  regra_dias_semana int[],               -- 0=segunda .. 6=domingo
  regra_dia_mes int,                     -- 1-31
  regra_meses int[],                     -- meses elegiveis (1-12), null = todos
  ativo boolean not null default true,
  criado_em timestamptz default now(),
  atualizado_em timestamptz default now()
);
alter table public.compromissos_definicoes enable row level security;
create policy "anon full access" on public.compromissos_definicoes for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.compromissos_definicoes;

create table public.compromissos_entregas (
  id bigint generated by default as identity primary key,
  definicao_id bigint references public.compromissos_definicoes(id) on delete cascade,
  data date not null,
  status text not null default 'pendente',   -- 'pendente' | 'entregue'
  entregue_em timestamptz,
  entregue_por text,
  criado_em timestamptz default now(),
  unique (definicao_id, data)
);
alter table public.compromissos_entregas enable row level security;
create policy "anon full access" on public.compromissos_entregas for all to anon using (true) with check (true);
alter publication supabase_realtime add table public.compromissos_entregas;

NOTIFY pgrst, 'reload schema';
